# wrangler.toml (put at project root or backend root depending on deployment)
name = "agrinetwork-app"
main = "worker/index.js"
compatibility_date = "2025-09-01"

# D1 binding
[[d1_databases]]
binding = "DB"
database_name = "agrinetwork_db"
database_id = "REPLACE_WITH_YOUR_D1_ID"

# KV binding (for notifications/caches)
[[kv_namespaces]]
binding = "APP_KV"
id = "REPLACE_WITH_YOUR_KV_ID"

# R2 binding (optional for images/files)
[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "REPLACE_WITH_YOUR_R2_BUCKET_NAME"